
project_id = "hshfqxjrilqzjpkcotgz"
[functions.admin-company-credit]
verify_jwt = true

[functions.company-credit]
verify_jwt = true

[functions.admin-payment-plans]
verify_jwt = true

[functions.company-payment-plans]
verify_jwt = true

[functions.add-billing-receivables]
verify_jwt = true

[functions.admin-remove-billing-receivable]
verify_jwt = true
