
project_id = "hshfqxjrilqzjpkcotgz"
[functions.admin-company-credit]
verify_jwt = true

[functions.company-credit]
verify_jwt = true

[functions.admin-payment-plans]
verify_jwt = true

[functions.company-payment-plans]
verify_jwt = true

[functions.add-billing-receivables]
verify_jwt = true

[functions.indexes-management]
verify_jwt = true

[functions.admin-boletos]
verify_jwt = true

[functions.company-boletos]
verify_jwt = true
